config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'invoices#index'

  get 'pendingbills', to: 'invoices#pending'
  get 'collectedbills', to: 'invoices#collected'
  resources :invoices, only: [:index, :new, :create, :show] do
    resources :collections, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :invoice, foreign_key: :reference, primary_key: :reference, inverse_of: :collections

  validates :reference, :amount, :collection_date, presence: true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :collections, foreign_key: :reference, primary_key: :reference, inverse_of: :invoice

  validates :brand_manager, :customer_name, :amount, :narration, :invoice_date, presence: true


  def balance_due(invoice)
    invoice.amount - invoice.collections.sum(&:amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_invoice

  def new
    @collection = @invoice.collections.new
  end

  def create
    @collection = @invoice.collections.create(collection_params)
    redirect_to invoice_path(@invoice)
  end



  private
  def collection_params
    params.require(:collection).permit(:reference, :amount, :collection_date)
  end

  def set_invoice
    @invoice = Invoice.find_by(id: params[:invoice_id])
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  def index
    @invoices = Invoice.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 25)
  end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoice_params)
    if @invoice.save
      redirect_to invoices_path
    else
      render new_invoice_path
    end
  end

  def show
    @invoice = Invoice.find(params[:id])
  end

  def pending
    @invoices = Invoice.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 25)
  end

  def collected
    @invoices = Invoice.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 25)
  end

  private
  def invoice_params
    params.require(:invoice).permit(:invoice_date, :narration, :amount, :customer_name, :reference, :brand_manager)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/collections/new.html.erb
<%= link_to 'Back', invoices_path, class: "btn btn-primary", style: "margin-left: 50px; margin-top: 20px;" %>
<div class="container" style=" margin-top: 35px; width: 25%; margin-left: 90px">
  <%= form_with model: [@invoice, @collection] do |f| %>
    <div>
        <label for="References" %> Reference</label>
        <%= f.text_field :reference, class: "form-control" %>
      </div>

    <div>
        <label for="collection_date" %> Collection Date</label>
        <%= f.text_field :collection_date, class: "form-control" %>
      </div>

    <div class="field">
      <label for="amount" %> Amount</label>
        <%= f.text_field :amount, class: "form-control" %>
      </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/invoices/_invoice_table.html.erb
<table class="table"  id="invoiceTable", style="margin-left: 25px;">
  <thead>
  <th> Reference</th>
  <th> Invoice Date</th>
  <th>Customer</th>
  <th> Brand manager</th>
  <th>Narration</th>
  <th>Amount</th>
  <th>Total Collection</th>
  <th>Balance Due</th>
  <th>Button Add to collection</th>
  </thead>
  <tbody>
  <% @invoices.each do |invoice| %>
    <tr>
      <%# if invoice.balance_due(invoice) > 0 %>
      <%# end %>
      <%# if invoice.balance_due(invoice) == 0 %>
      <%# end %>
      <td> <%= link_to invoice.reference, invoice_path(invoice) %></td>
      <td>  <%= invoice.invoice_date %></td>
      <td> <%= invoice.customer_name %></td>
      <td> <%= invoice.brand_manager %></td>
      <td> <%= invoice.narration %></td>
      <td> <%= invoice.amount %></td>
      <td><%= invoice.collections.sum(&:amount) %></td>
      <td> <%= invoice.balance_due(invoice) %></td>
      <% unless invoice.balance_due(invoice) == 0 %>
        <td><%= link_to 'Add Collection', new_invoice_collection_path(invoice), class: "btn btn-primary" %> </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/invoices/collected.html.erb
<%= link_to 'Add new bill', new_invoice_path, class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<%= link_to 'All Bills', invoices_path, class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<%= link_to 'Show Pending bills', pendingbills_path, class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<%= link_to 'show Collected bills', collectedbills_path, class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<span style="margin-left: 50px;">
  <%= will_paginate @invoice, style: "margin-left: 450px; margin-top: 20px" %>
</span>

<table class="table" id="invoiceTable" , style="margin-left: 25px;">
  <thead>
  <th> Reference</th>
  <th> Invoice Date</th>
  <th>Customer</th>
  <th> Brand manager</th>
  <th>Narration</th>
  <th>Amount</th>
  <th>Total Collection</th>
  <th>Balance Due</th>
  </thead>
  <tbody>
  <% @invoices.each do |invoice| %>
    <% if invoice.balance_due(invoice) == 0 %>
      <tr>
        <td> <%= link_to invoice.reference, invoice_path(invoice) %></td>
        <td>  <%= invoice.invoice_date %></td>
        <td> <%= invoice.customer_name %></td>
        <td> <%= invoice.brand_manager %></td>
        <td> <%= invoice.narration %></td>
        <td> <%= invoice.amount %></td>
        <td><%= invoice.collections.sum(&:amount) %></td>
        <td> <%= invoice.balance_due(invoice) %></td>
        <% unless invoice.balance_due(invoice) == 0 %>
          <td><%= link_to 'Add Collection', new_invoice_collection_path(invoice), class: "btn btn-primary" %> </td>
        <% end %>
    <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @invoice, style: "margin-left: 450px;" %>

app/views/invoices/index.html.erb
<%= link_to 'Add new bill', new_invoice_path, class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<%= link_to 'All bills', invoices_path, class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<%= link_to 'Show Pending bills', pendingbills_path(@invoice), class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<%= link_to 'show Collected bills', collectedbills_path(@invoice), class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<span style="margin-left: 50px;">
  <%= will_paginate @invoice, style: "margin-left: 450px; margin-top: 20px" %>
</span>

<table class="table" id="invoiceTable" , style="margin-left: 25px;">
  <thead>
  <th> Reference</th>
  <th> Invoice Date</th>
  <th>Customer</th>
  <th> Brand manager</th>
  <th>Narration</th>
  <th>Amount</th>
  <th>Total Collection</th>
  <th>Balance Due</th>
  <th>Button Add to collection</th>
  </thead>
  <tbody>
  <% @invoices.each do |invoice| %>
    <tr>
      <% if invoice.balance_due(invoice) > 0 %>
        <td> <%= link_to invoice.reference, invoice_path(invoice) %></td>
        <td>  <%= invoice.invoice_date %></td>
        <td> <%= invoice.customer_name %></td>
        <td> <%= invoice.brand_manager %></td>
        <td> <%= invoice.narration %></td>
        <td> <%= invoice.amount %></td>
        <td><%= invoice.collections.sum(&:amount) %></td>
        <td> <%= invoice.balance_due(invoice) %></td>
        <% unless invoice.balance_due(invoice) == 0 %>
          <td><%= link_to 'Add Collection', new_invoice_collection_path(invoice), class: "btn btn-primary" %> </td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @invoice, style: "margin-left: 450px;" %>

app/views/invoices/new.html.erb
<%= link_to 'Back', invoices_path, class: "btn btn-primary", style: "margin-left: 50px; margin-top: 20px;" %>

<div class="container" style="margin-top: 30px; width: 25%; margin-left: 90px;">
  <%= form_with model: [@invoice] do |f| %>
    <div>
      <label for="References" %> Reference</label>
      <%= f.text_field :reference, class: "form-control" %>
    </div>

    <div>
      <label for="InvoiceDate" %>Invoice Date</label>
      <%= f.text_field :invoice_date, class: "form-control" %>
    </div>

    <div>
      <label for="Customer" %> Customer name</label>
      <%= f.text_field :customer_name, class: "form-control" %>
    </div>

    <div>
      <label for="brand_manager" %> Brand Manager</label>
      <%= f.text_field :brand_manager, class: "form-control" %>
    </div>

    <div>
      <label for="narration" %> Narration</label>
      <%= f.text_field :narration, class: "form-control" %>
    </div>

    <div>
      <label for="amount" %> amount</label>
      <%= f.text_field :amount, class: "form-control" %>
    </div>

    <%= f.submit %>

  <% end %>
</div>

app/views/invoices/pending.html.erb
<%= link_to 'Add new bill', new_invoice_path, class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<%= link_to 'All bills', invoices_path, class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<%= link_to 'Show Pending bills', pendingbills_path, class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<%= link_to 'show Collected bills', collectedbills_path, class: "btn btn-primary", style: "margin-left: 150px; margin-top: 70px;" %>
<span style="margin-left: 50px;">
  <%= will_paginate @invoice, style: "margin-left: 450px; margin-top: 20px" %>
</span>

<table class="table" id="invoiceTable" , style="margin-left: 25px;">
  <thead>
  <th> Reference</th>
  <th> Invoice Date</th>
  <th>Customer</th>
  <th> Brand manager</th>
  <th>Narration</th>
  <th>Amount</th>
  <th>Total Collection</th>
  <th>Balance Due</th>
  <th>Button Add to collection</th>
  </thead>
  <tbody>
  <% @invoices.each do |invoice| %>
    <% if invoice.balance_due(invoice) > 0 %>
    <tr>
        <td> <%= link_to invoice.reference, invoice_path(invoice) %></td>
        <td>  <%= invoice.invoice_date %></td>
        <td> <%= invoice.customer_name %></td>
        <td> <%= invoice.brand_manager %></td>
        <td> <%= invoice.narration %></td>
        <td> <%= invoice.amount %></td>
        <td><%= invoice.collections.sum(&:amount) %></td>
        <td> <%= invoice.balance_due(invoice) %></td>
        <% unless invoice.balance_due(invoice) == 0 %>
          <td><%= link_to 'Add Collection', new_invoice_collection_path(invoice), class: "btn btn-primary" %> </td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<%#= will_paginate @invoice, style: "margin-left: 450px;" %>

app/views/invoices/show.html.erb
<%= link_to 'Back', invoices_path, class: "btn btn-primary", style: "margin-left: 40px; margin-top: 20px"; %>
<div class="show-invoice" style="margin-left: 20px; padding-top: 30px;">
  <p class="text-primary"> <%= @invoice.reference %></p>
  <p> <%= @invoice.customer_name %></p>
  <p> <%= @invoice.brand_manager %></p>
  <p><%= @invoice.narration %></p>
</div>

<table class="table" id= "CollectionTable" style="margin-left: 80px; margin-top: 45px;  width: 50%;">
  <thead>
  <th> Date</th>
  <th> Event</th>
  <th> Amount</th>
  </thead>
  <tbody>
  <tr>
    <td><%= @invoice.invoice_date %></td>
    <td> New Invoice</td>
    <td><%= @invoice.amount %></td>

  </tr>
  <% @invoice.collections.each do |collection| %>
    <tr>

      <td><%= collection.collection_date %></td>
      <td> Collection</td>
      <td><%= collection.amount %></td>
    </tr>
  <% end %>
  <tr>
    <td></td>
    <td> Balance</td>
    <td> <%= @invoice.balance_due(@invoice) %></td>
  </tr>

  </tbody>

</table>

<p> <%= link_to 'Add Collection', new_invoice_collection_path(@invoice), class: "btn btn-primary", style: "margin-left: 65px; margin-top: 10px" %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tally</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>